apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
- name: credential-provider-oke
  apiVersion: credentialprovider.kubelet.k8s.io/v1
  matchImages:
  - "*.ocir.io"
  defaultCacheDuration: 55m
  env:
  - name: REGISTRY_TOKEN_PATH
    value: /20180419/docker/token
  - name: DEFAULT_USER
    value: BEARER_TOKEN
  - name: REGISTRY_PROTOCOL
    value: https
  - name: OCIR_AUTH_METHOD
    value: INSTANCE_PRINCIPAL
    